# Generated by Django 3.2.5 on 2022-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClassifySkin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
